theme: jekyll-theme-dinky
title: Sharon 4 the People
description: > # this means to ignore newlines until "baseurl:"
  Sharon Cummings is running for Williamson County Commissioner Precinct 3 as a Democrat that will work for the people.
