theme: jekyll-theme-cayman
title: Sharon 4 the People
description: > # this means to ignore newlines until "baseurl:"
  Sharon Cummings is running for Williamson County Judge as a Democrat that will work for the people.
